/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/bookshelf/bookshelf.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[2, 0.06, 0.6]}>
        <mesh material={materials.phong1} geometry={nodes.pCube1.geometry} />
      </group>
      <group position={[0, 0.71, 0]} scale={[2, 0.06, 0.6]}>
        <mesh material={materials.phong1} geometry={nodes.pCube2.geometry} />
      </group>
      <group position={[0, 1.42, 0]} scale={[2, 0.06, 0.6]}>
        <mesh material={materials.phong1} geometry={nodes.pCube3.geometry} />
      </group>
      <group position={[0, 2.13, 0]} scale={[2, 0.06, 0.6]}>
        <mesh material={materials.phong1} geometry={nodes.pCube4.geometry} />
      </group>
      <group position={[1.03, 1.21, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[2, 0.06, 0.6]}>
        <mesh material={materials.phong1} geometry={nodes.pCube5.geometry} />
      </group>
      <group position={[-1.03, 1.21, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[2, 0.06, 0.6]}>
        <mesh material={materials.phong1} geometry={nodes.pCube6.geometry} />
      </group>
      <group position={[0, 1, -0.31]} scale={[2.12, 2.32, 0.02]}>
        <mesh material={materials.phong1} geometry={nodes.pCube7.geometry} />
      </group>
    </group>
  )
}
