/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, 'doorframe/doorframe.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[1.02, 1.88, 0]} scale={[2.24, 3.74, 0.33]}>
        <mesh material={materials.phong1} geometry={nodes.pCube2.geometry} />
      </group>
    </group>
  )
}
