/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, 'wall/wall.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 4.81, 6.96]} scale={[24.39, 9.62, 0.02]}>
        <mesh material={materials.phong1} geometry={nodes.pCube3.geometry} />
      </group>
    </group>
  )
}
